[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[env]
_.python.venv = { path = ".venv", create = true }

[tools]

[tools."http:arduino-cli"]
version = "1.2.2"

[tools."http:arduino-cli".platforms]
linux-x64 = { url = "https://github.com/arduino/arduino-cli/releases/download/v{version}/arduino-cli_{version}_Linux_64bit.tar.gz" }

[tasks."setup"]
run = """
#!/usr/bin/env bash
if [ ! -f ".env" ]; then
  cp .env.example .env
fi

arduino-cli core update-index --config-file arduino-cli.yaml
arduino-cli lib  update-index --config-file arduino-cli.yaml

arduino-cli core install esp32-bluepad32:esp32 --config-file arduino-cli.yaml
arduino-cli core install esp32:esp32 --config-file arduino-cli.yaml
"""